### ISSUE TITLE
Some problems were encountered while replicating the code

### ISSUE THREAD

**Issue by chendan094** [claws-lab/MisinfoCorrect#2]
Hi.
When I try to reproduce the results of the code, in “src/lsp_model_rl/coherence_classifier2.py”, how can i get the model_path "politeness_clf_fp" that indicates "./../../MisinfoCorrect_support_models/politeness_clf.pt"

**Comment by binghe2727** [comment]
Hi,

Thanks for your interest in our work. 

For your question, the model path is the place where you saved the trained politeness classifier. You first train different classifiers and then the RL framework calls these classifiers to build the text generator. Regarding how to train these classifiers, the details are covered in the paper. If you have any questions, please let us know. Thanks.
